### ISSUE TITLE
migest no longer available from CRAN

### ISSUE THREAD

**Issue by lejarx** [guyabel/migest#1]
Hi @guyabel,

I stumbled upon your excellent post on chord diagram and wanted to follow through it.
https://guyabel.com/post/animated-directional-chord-diagrams/

Though it seems `migest` is no longer available through CRAN, I also tried installing from `github` , `install_github("guyabel/migest")`, but doesn't seem possible due to `rlang`.
Any possibility of having a new compiled version of `migest`?

Thank you

**Comment by guyabel** [comment]
Back on CRAN. Apologies for the delay.
